/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.4-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package eu.stefanangelov.chatbot.botservice.controller;

import eu.stefanangelov.chatbot.botservice.to.BotResponse;
import eu.stefanangelov.chatbot.botservice.to.UserMessage;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-26T20:27:12.373Z[GMT]")

@Api(value = "messages", description = "the messages API")
public interface MessagesApi {

    @ApiOperation(value = "Send message to the bot", nickname = "messagesPost", notes = "", response = BotResponse.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BotResponse.class),
        @ApiResponse(code = 400, message = "Invalid data is sended"),
        @ApiResponse(code = 500, message = "Unexpected error.") })
    @RequestMapping(value = "/messages",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<BotResponse> messagesPost(@ApiParam(value = "Body request contain information about user message", required = true) @Valid @RequestBody UserMessage body);

}
