/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.4-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package eu.stefanangelov.chatbot.chatservice.controller;

import eu.stefanangelov.chatbot.chatservice.to.MessageTO;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2018-12-26T11:59:47.122Z[GMT]")

@Api(value = "messages", description = "the messages API")
public interface MessagesApi {

    @ApiOperation(value = "Get all user messages", nickname = "messagesGet", notes = "", responseContainer = "List",
            response = MessageTO.class, authorizations = {
            @Authorization(value = "bearerAuth")
    }, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = MessageTO.class),
            @ApiResponse(code = 401, message = "Authorization information is missing or invalid."),
            @ApiResponse(code = 500, message = "Unexpected error.")})
    @RequestMapping(value = "/messages",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<List<MessageTO>> messagesGet(@ApiParam(value = "subset of the results to return") @Valid @RequestParam(value = "queryRange", required = false) Integer queryRange);

}
