name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven (Bot Service)
      run: mvn -B package --file bot-service/pom.xml
    - name: Build with Maven (ChatService)
      run: mvn -B package --file chat-service/pom.xml
    - name: Build with Maven (supply-chain-service)
      run: mvn -B package --file supply-chain-service/pom.xml
